import type { Metadata } from 'next'
import { cookies } from 'next/headers'
import { Providers } from './providers'
import '../styles.css'

export const metadata: Metadata = {
  title: 'Inventory Management',
  description: 'Generated by Lovable (Migrated to Next.js)',
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const cookieStore = await cookies()
  const locale = (cookieStore.get('locale')?.value || 'ar') as 'ar' | 'en'
  const dir = locale === 'ar' ? 'rtl' : 'ltr'

  return (
    <html lang={locale} dir={dir}>
      <body className="antialiased">
        <Providers defaultLocale={locale}>
          {children}
        </Providers>
      </body>
    </html>
  )
}
