-- Fix pg_graphql exposures
REVOKE SELECT ON ALL TABLES IN SCHEMA public FROM anon;

-- Fix Security Definer Functions
REVOKE EXECUTE ON FUNCTION public.admin_delete_user_data(uuid, uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.admin_update_profile(uuid, uuid, text, text, boolean) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.audit_log_row_change() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.handle_new_user() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.prevent_currency_code_update() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.set_audit_changed_by(uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.has_permission(uuid, text) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.is_admin(uuid) FROM PUBLIC;

GRANT EXECUTE ON FUNCTION public.admin_delete_user_data(uuid, uuid) TO service_role;
GRANT EXECUTE ON FUNCTION public.admin_update_profile(uuid, uuid, text, text, boolean) TO service_role;
GRANT EXECUTE ON FUNCTION public.has_permission(uuid, text) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.is_admin(uuid) TO authenticated, service_role;

-- Fix missing search_path
ALTER FUNCTION public.audit_log_diff(jsonb, jsonb) SET search_path = '';
ALTER FUNCTION public.prevent_currency_code_update() SET search_path = '';
ALTER FUNCTION public.set_audit_changed_by(uuid) SET search_path = '';

-- Add missing foreign key indexes
CREATE INDEX IF NOT EXISTS permission_group_items_group_id_idx ON public.permission_group_items(group_id);
CREATE INDEX IF NOT EXISTS permission_group_items_permission_key_idx ON public.permission_group_items(permission_key);
CREATE INDEX IF NOT EXISTS profiles_id_idx ON public.profiles(id);
CREATE INDEX IF NOT EXISTS user_permissions_user_id_idx ON public.user_permissions(user_id);
CREATE INDEX IF NOT EXISTS user_permissions_permission_key_idx ON public.user_permissions(permission_key);
CREATE INDEX IF NOT EXISTS user_permission_groups_user_id_idx ON public.user_permission_groups(user_id);
CREATE INDEX IF NOT EXISTS user_permission_groups_group_id_idx ON public.user_permission_groups(group_id);
CREATE INDEX IF NOT EXISTS exchange_rates_currency_code_idx ON public.exchange_rates(currency_code);
CREATE INDEX IF NOT EXISTS exchange_rates_created_by_idx ON public.exchange_rates(created_by);
CREATE INDEX IF NOT EXISTS categories_parent_id_idx ON public.categories(parent_id);
CREATE INDEX IF NOT EXISTS categories_created_by_idx ON public.categories(created_by);
CREATE INDEX IF NOT EXISTS categories_updated_by_idx ON public.categories(updated_by);
CREATE INDEX IF NOT EXISTS items_category_id_idx ON public.items(category_id);
CREATE INDEX IF NOT EXISTS items_unit_id_idx ON public.items(unit_id);
CREATE INDEX IF NOT EXISTS items_created_by_idx ON public.items(created_by);
CREATE INDEX IF NOT EXISTS items_updated_by_idx ON public.items(updated_by);
CREATE INDEX IF NOT EXISTS suppliers_created_by_idx ON public.suppliers(created_by);
CREATE INDEX IF NOT EXISTS suppliers_updated_by_idx ON public.suppliers(updated_by);
CREATE INDEX IF NOT EXISTS customers_created_by_idx ON public.customers(created_by);
CREATE INDEX IF NOT EXISTS customers_updated_by_idx ON public.customers(updated_by);
CREATE INDEX IF NOT EXISTS purchase_invoices_supplier_id_idx ON public.purchase_invoices(supplier_id);
CREATE INDEX IF NOT EXISTS purchase_invoices_currency_code_idx ON public.purchase_invoices(currency_code);
CREATE INDEX IF NOT EXISTS purchase_invoices_created_by_idx ON public.purchase_invoices(created_by);
CREATE INDEX IF NOT EXISTS purchase_invoices_updated_by_idx ON public.purchase_invoices(updated_by);
CREATE INDEX IF NOT EXISTS purchase_invoice_items_invoice_id_idx ON public.purchase_invoice_items(invoice_id);
CREATE INDEX IF NOT EXISTS purchase_invoice_items_item_id_idx ON public.purchase_invoice_items(item_id);
CREATE INDEX IF NOT EXISTS stock_movements_item_id_idx ON public.stock_movements(item_id);
CREATE INDEX IF NOT EXISTS stock_movements_created_by_idx ON public.stock_movements(created_by);
CREATE INDEX IF NOT EXISTS debt_transactions_customer_id_idx ON public.debt_transactions(customer_id);
CREATE INDEX IF NOT EXISTS debt_transactions_currency_code_idx ON public.debt_transactions(currency_code);
CREATE INDEX IF NOT EXISTS debt_transactions_created_by_idx ON public.debt_transactions(created_by);
CREATE INDEX IF NOT EXISTS debt_transactions_updated_by_idx ON public.debt_transactions(updated_by);
CREATE INDEX IF NOT EXISTS audit_logs_changed_by_idx ON public.audit_logs(changed_by);
CREATE INDEX IF NOT EXISTS purchase_invoice_items_created_by_idx ON public.purchase_invoice_items(created_by);
CREATE INDEX IF NOT EXISTS purchase_invoice_items_updated_by_idx ON public.purchase_invoice_items(updated_by);
CREATE INDEX IF NOT EXISTS suppliers_default_currency_idx ON public.suppliers(default_currency);
CREATE INDEX IF NOT EXISTS profiles_created_by_idx ON public.profiles(created_by);
CREATE INDEX IF NOT EXISTS profiles_updated_by_idx ON public.profiles(updated_by);
CREATE INDEX IF NOT EXISTS user_permissions_created_by_idx ON public.user_permissions(created_by);
CREATE INDEX IF NOT EXISTS user_permission_groups_created_by_idx ON public.user_permission_groups(created_by);
CREATE INDEX IF NOT EXISTS item_images_created_by_idx ON public.item_images(created_by);
CREATE INDEX IF NOT EXISTS item_images_item_id_idx ON public.item_images(item_id);
CREATE INDEX IF NOT EXISTS item_units_created_by_idx ON public.item_units(created_by);
CREATE INDEX IF NOT EXISTS item_units_item_id_idx ON public.item_units(item_id);
CREATE INDEX IF NOT EXISTS item_units_unit_id_idx ON public.item_units(unit_id);
CREATE INDEX IF NOT EXISTS purchase_invoice_items_item_unit_id_idx ON public.purchase_invoice_items(item_unit_id);

-- Fix RLS Policies by wrapping auth.uid() in (select auth.uid())
ALTER POLICY "self update profile" ON public.profiles TO authenticated USING ((id = (select auth.uid()))) ;
ALTER POLICY "admins manage profiles" ON public.profiles TO authenticated USING (has_permission((select auth.uid()), 'users.manage'::text)) WITH CHECK (has_permission((select auth.uid()), 'users.manage'::text)) ;
ALTER POLICY "manage pgroups" ON public.permission_groups TO authenticated USING (has_permission((select auth.uid()), 'permissions.manage'::text)) WITH CHECK (has_permission((select auth.uid()), 'permissions.manage'::text)) ;
ALTER POLICY "manage pgi" ON public.permission_group_items TO authenticated USING (has_permission((select auth.uid()), 'permissions.manage'::text)) WITH CHECK (has_permission((select auth.uid()), 'permissions.manage'::text)) ;
ALTER POLICY "manage up" ON public.user_permissions TO authenticated USING (has_permission((select auth.uid()), 'permissions.manage'::text)) WITH CHECK (has_permission((select auth.uid()), 'permissions.manage'::text)) ;
ALTER POLICY "manage upg" ON public.user_permission_groups TO authenticated USING (has_permission((select auth.uid()), 'permissions.manage'::text)) WITH CHECK (has_permission((select auth.uid()), 'permissions.manage'::text)) ;
ALTER POLICY "perm write currencies" ON public.currencies TO authenticated WITH CHECK (has_permission((select auth.uid()), 'settings.manage'::text)) ;
ALTER POLICY "perm update currencies" ON public.currencies TO authenticated USING (has_permission((select auth.uid()), 'settings.manage'::text)) WITH CHECK (has_permission((select auth.uid()), 'settings.manage'::text)) ;
ALTER POLICY "perm delete currencies" ON public.currencies TO authenticated USING (has_permission((select auth.uid()), 'settings.manage'::text)) ;
ALTER POLICY "perm write exchange_rates" ON public.exchange_rates TO authenticated WITH CHECK (has_permission((select auth.uid()), 'settings.manage'::text)) ;
ALTER POLICY "perm update exchange_rates" ON public.exchange_rates TO authenticated USING (has_permission((select auth.uid()), 'settings.manage'::text)) WITH CHECK (has_permission((select auth.uid()), 'settings.manage'::text)) ;
ALTER POLICY "perm delete exchange_rates" ON public.exchange_rates TO authenticated USING (has_permission((select auth.uid()), 'settings.manage'::text)) ;
ALTER POLICY "perm write units" ON public.units TO authenticated WITH CHECK (has_permission((select auth.uid()), 'settings.manage'::text)) ;
ALTER POLICY "perm update units" ON public.units TO authenticated USING (has_permission((select auth.uid()), 'settings.manage'::text)) WITH CHECK (has_permission((select auth.uid()), 'settings.manage'::text)) ;
ALTER POLICY "perm delete units" ON public.units TO authenticated USING (has_permission((select auth.uid()), 'settings.manage'::text)) ;
ALTER POLICY "perm write categories" ON public.categories TO authenticated WITH CHECK (has_permission((select auth.uid()), 'items.manage'::text)) ;
ALTER POLICY "perm update categories" ON public.categories TO authenticated USING (has_permission((select auth.uid()), 'items.manage'::text)) WITH CHECK (has_permission((select auth.uid()), 'items.manage'::text)) ;
ALTER POLICY "perm delete categories" ON public.categories TO authenticated USING (has_permission((select auth.uid()), 'items.manage'::text)) ;
ALTER POLICY "perm write items" ON public.items TO authenticated WITH CHECK (has_permission((select auth.uid()), 'items.manage'::text)) ;
ALTER POLICY "perm update items" ON public.items TO authenticated USING (has_permission((select auth.uid()), 'items.manage'::text)) WITH CHECK (has_permission((select auth.uid()), 'items.manage'::text)) ;
ALTER POLICY "perm delete items" ON public.items TO authenticated USING (has_permission((select auth.uid()), 'items.manage'::text)) ;
ALTER POLICY "perm write suppliers" ON public.suppliers TO authenticated WITH CHECK (has_permission((select auth.uid()), 'suppliers.manage'::text)) ;
ALTER POLICY "perm update suppliers" ON public.suppliers TO authenticated USING (has_permission((select auth.uid()), 'suppliers.manage'::text)) WITH CHECK (has_permission((select auth.uid()), 'suppliers.manage'::text)) ;
ALTER POLICY "perm delete suppliers" ON public.suppliers TO authenticated USING (has_permission((select auth.uid()), 'suppliers.manage'::text)) ;
ALTER POLICY "perm write customers" ON public.customers TO authenticated WITH CHECK (has_permission((select auth.uid()), 'customers.manage'::text)) ;
ALTER POLICY "perm update customers" ON public.customers TO authenticated USING (has_permission((select auth.uid()), 'customers.manage'::text)) WITH CHECK (has_permission((select auth.uid()), 'customers.manage'::text)) ;
ALTER POLICY "perm delete customers" ON public.customers TO authenticated USING (has_permission((select auth.uid()), 'customers.manage'::text)) ;
ALTER POLICY "perm write purchase_invoices" ON public.purchase_invoices TO authenticated WITH CHECK (has_permission((select auth.uid()), 'invoices.manage'::text)) ;
ALTER POLICY "perm update purchase_invoices" ON public.purchase_invoices TO authenticated USING (has_permission((select auth.uid()), 'invoices.manage'::text)) WITH CHECK (has_permission((select auth.uid()), 'invoices.manage'::text)) ;
ALTER POLICY "perm delete purchase_invoices" ON public.purchase_invoices TO authenticated USING (has_permission((select auth.uid()), 'invoices.manage'::text)) ;
ALTER POLICY "perm write purchase_invoice_items" ON public.purchase_invoice_items TO authenticated WITH CHECK (has_permission((select auth.uid()), 'invoices.manage'::text)) ;
ALTER POLICY "perm update purchase_invoice_items" ON public.purchase_invoice_items TO authenticated USING (has_permission((select auth.uid()), 'invoices.manage'::text)) WITH CHECK (has_permission((select auth.uid()), 'invoices.manage'::text)) ;
ALTER POLICY "perm delete purchase_invoice_items" ON public.purchase_invoice_items TO authenticated USING (has_permission((select auth.uid()), 'invoices.manage'::text)) ;
ALTER POLICY "perm write stock_movements" ON public.stock_movements TO authenticated WITH CHECK (has_permission((select auth.uid()), 'invoices.manage'::text)) ;
ALTER POLICY "perm update stock_movements" ON public.stock_movements TO authenticated USING (has_permission((select auth.uid()), 'invoices.manage'::text)) WITH CHECK (has_permission((select auth.uid()), 'invoices.manage'::text)) ;
ALTER POLICY "perm delete stock_movements" ON public.stock_movements TO authenticated USING (has_permission((select auth.uid()), 'invoices.manage'::text)) ;
ALTER POLICY "perm write debt_transactions" ON public.debt_transactions TO authenticated WITH CHECK (has_permission((select auth.uid()), 'debts.manage'::text)) ;
ALTER POLICY "perm update debt_transactions" ON public.debt_transactions TO authenticated USING (has_permission((select auth.uid()), 'debts.manage'::text)) WITH CHECK (has_permission((select auth.uid()), 'debts.manage'::text)) ;
ALTER POLICY "perm delete debt_transactions" ON public.debt_transactions TO authenticated USING (has_permission((select auth.uid()), 'debts.manage'::text)) ;
ALTER POLICY "auth read audit_logs" ON public.audit_logs TO authenticated USING (has_permission((select auth.uid()), 'system.admin'::text)) ;
ALTER POLICY "perm delete item_images" ON public.item_images TO authenticated USING (has_permission((select auth.uid()), 'items.manage'::text)) ;
ALTER POLICY "perm insert item_images" ON public.item_images TO authenticated WITH CHECK (has_permission((select auth.uid()), 'items.manage'::text)) ;
ALTER POLICY "perm update item_images" ON public.item_images TO authenticated USING (has_permission((select auth.uid()), 'items.manage'::text)) WITH CHECK (has_permission((select auth.uid()), 'items.manage'::text)) ;
ALTER POLICY "perm delete item_units" ON public.item_units TO authenticated USING (has_permission((select auth.uid()), 'items.manage'::text)) ;
ALTER POLICY "perm insert item_units" ON public.item_units TO authenticated WITH CHECK (has_permission((select auth.uid()), 'items.manage'::text)) ;
ALTER POLICY "perm update item_units" ON public.item_units TO authenticated USING (has_permission((select auth.uid()), 'items.manage'::text)) WITH CHECK (has_permission((select auth.uid()), 'items.manage'::text)) ;
ALTER POLICY "user update own profile avatar" ON public.profiles TO authenticated USING ((id = (select auth.uid()))) WITH CHECK ((id = (select auth.uid()))) ;
