ALTER POLICY "auth delete item-images" ON storage.objects USING (((bucket_id = 'item-images'::text) AND current_user_has_permission('items.manage'::text))) ;
ALTER POLICY "auth upload item-images" ON storage.objects  WITH CHECK (((bucket_id = 'item-images'::text) AND current_user_has_permission('items.manage'::text)));
ALTER POLICY "admins manage profiles" ON public.profiles USING (current_user_has_permission( 'users.manage'::text)) WITH CHECK (current_user_has_permission( 'users.manage'::text));
ALTER POLICY "manage pgroups" ON public.permission_groups USING (current_user_has_permission( 'permissions.manage'::text)) WITH CHECK (current_user_has_permission( 'permissions.manage'::text));
ALTER POLICY "manage pgi" ON public.permission_group_items USING (current_user_has_permission( 'permissions.manage'::text)) WITH CHECK (current_user_has_permission( 'permissions.manage'::text));
ALTER POLICY "manage up" ON public.user_permissions USING (current_user_has_permission( 'permissions.manage'::text)) WITH CHECK (current_user_has_permission( 'permissions.manage'::text));
ALTER POLICY "manage upg" ON public.user_permission_groups USING (current_user_has_permission( 'permissions.manage'::text)) WITH CHECK (current_user_has_permission( 'permissions.manage'::text));
ALTER POLICY "perm write currencies" ON public.currencies  WITH CHECK (current_user_has_permission( 'settings.manage'::text));
ALTER POLICY "perm update currencies" ON public.currencies USING (current_user_has_permission( 'settings.manage'::text)) WITH CHECK (current_user_has_permission( 'settings.manage'::text));
ALTER POLICY "perm delete currencies" ON public.currencies USING (current_user_has_permission( 'settings.manage'::text)) ;
ALTER POLICY "perm write exchange_rates" ON public.exchange_rates  WITH CHECK (current_user_has_permission( 'settings.manage'::text));
ALTER POLICY "perm update exchange_rates" ON public.exchange_rates USING (current_user_has_permission( 'settings.manage'::text)) WITH CHECK (current_user_has_permission( 'settings.manage'::text));
ALTER POLICY "perm delete exchange_rates" ON public.exchange_rates USING (current_user_has_permission( 'settings.manage'::text)) ;
ALTER POLICY "perm write units" ON public.units  WITH CHECK (current_user_has_permission( 'settings.manage'::text));
ALTER POLICY "perm update units" ON public.units USING (current_user_has_permission( 'settings.manage'::text)) WITH CHECK (current_user_has_permission( 'settings.manage'::text));
ALTER POLICY "perm delete units" ON public.units USING (current_user_has_permission( 'settings.manage'::text)) ;
ALTER POLICY "perm write categories" ON public.categories  WITH CHECK (current_user_has_permission( 'items.manage'::text));
ALTER POLICY "perm update categories" ON public.categories USING (current_user_has_permission( 'items.manage'::text)) WITH CHECK (current_user_has_permission( 'items.manage'::text));
ALTER POLICY "perm delete categories" ON public.categories USING (current_user_has_permission( 'items.manage'::text)) ;
ALTER POLICY "perm write items" ON public.items  WITH CHECK (current_user_has_permission( 'items.manage'::text));
ALTER POLICY "perm update items" ON public.items USING (current_user_has_permission( 'items.manage'::text)) WITH CHECK (current_user_has_permission( 'items.manage'::text));
ALTER POLICY "perm delete items" ON public.items USING (current_user_has_permission( 'items.manage'::text)) ;
ALTER POLICY "perm write suppliers" ON public.suppliers  WITH CHECK (current_user_has_permission( 'suppliers.manage'::text));
ALTER POLICY "perm update suppliers" ON public.suppliers USING (current_user_has_permission( 'suppliers.manage'::text)) WITH CHECK (current_user_has_permission( 'suppliers.manage'::text));
ALTER POLICY "perm delete suppliers" ON public.suppliers USING (current_user_has_permission( 'suppliers.manage'::text)) ;
ALTER POLICY "perm write customers" ON public.customers  WITH CHECK (current_user_has_permission( 'customers.manage'::text));
ALTER POLICY "perm update customers" ON public.customers USING (current_user_has_permission( 'customers.manage'::text)) WITH CHECK (current_user_has_permission( 'customers.manage'::text));
ALTER POLICY "perm delete customers" ON public.customers USING (current_user_has_permission( 'customers.manage'::text)) ;
ALTER POLICY "perm write purchase_invoices" ON public.purchase_invoices  WITH CHECK (current_user_has_permission( 'invoices.manage'::text));
ALTER POLICY "perm update purchase_invoices" ON public.purchase_invoices USING (current_user_has_permission( 'invoices.manage'::text)) WITH CHECK (current_user_has_permission( 'invoices.manage'::text));
ALTER POLICY "perm delete purchase_invoices" ON public.purchase_invoices USING (current_user_has_permission( 'invoices.manage'::text)) ;
ALTER POLICY "perm write purchase_invoice_items" ON public.purchase_invoice_items  WITH CHECK (current_user_has_permission( 'invoices.manage'::text));
ALTER POLICY "perm update purchase_invoice_items" ON public.purchase_invoice_items USING (current_user_has_permission( 'invoices.manage'::text)) WITH CHECK (current_user_has_permission( 'invoices.manage'::text));
ALTER POLICY "perm delete purchase_invoice_items" ON public.purchase_invoice_items USING (current_user_has_permission( 'invoices.manage'::text)) ;
ALTER POLICY "perm write debt_transactions" ON public.debt_transactions  WITH CHECK (current_user_has_permission( 'debts.manage'::text));
ALTER POLICY "perm update debt_transactions" ON public.debt_transactions USING (current_user_has_permission( 'debts.manage'::text)) WITH CHECK (current_user_has_permission( 'debts.manage'::text));
ALTER POLICY "perm delete debt_transactions" ON public.debt_transactions USING (current_user_has_permission( 'debts.manage'::text)) ;
ALTER POLICY "auth read audit_logs" ON public.audit_logs USING (current_user_has_permission( 'system.admin'::text)) ;
ALTER POLICY "perm delete item_images" ON public.item_images USING (current_user_has_permission( 'items.manage'::text)) ;
ALTER POLICY "perm insert item_images" ON public.item_images  WITH CHECK (current_user_has_permission( 'items.manage'::text));
ALTER POLICY "perm update item_images" ON public.item_images USING (current_user_has_permission( 'items.manage'::text)) WITH CHECK (current_user_has_permission( 'items.manage'::text));
ALTER POLICY "perm delete item_units" ON public.item_units USING (current_user_has_permission( 'items.manage'::text)) ;
ALTER POLICY "perm insert item_units" ON public.item_units  WITH CHECK (current_user_has_permission( 'items.manage'::text));
ALTER POLICY "perm update item_units" ON public.item_units USING (current_user_has_permission( 'items.manage'::text)) WITH CHECK (current_user_has_permission( 'items.manage'::text));
